config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  resources :users, only: %i[] do
    resources :posts, only: %i[index]
  end

  resources :posts do
    resources :comments
  end
  resource :session
  resources :passwords, param: :token
  resources :searches, only: %i[index]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true

  def created_by?(user)
    self.user == user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def edit
    @post = Post.find(params[:post_id])
    @comment = Current.user.comments.find(params.expect(:id))
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Current.user.comments.build(comment_params.merge(post_id: @post.id))

    if @comment.save
      redirect_to @post, notice: "Comment was successfully created.", status: :see_other
    else
      redirect_to @post, alert: @comment.errors.full_messages.to_sentence, status: :see_other
    end
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Current.user.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to @post, notice: "Comment was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    post = Post.find(params[:post_id])
    comment = Current.user.comments.find(params[:id])
    comment.destroy!
    redirect_to post, notice: "Comment was successfully destroyed.", status: :see_other
  end

  private

  def comment_params
    params.expect(comment: [ :body ])
  end
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag comment do %>
  <article>
    <%= comment.body %>
    <hr>
    <%= time_ago_in_words(comment.created_at) %> ago
    by <%= comment.user.name %>
    <% if comment.created_by?(Current.user) %>
      <%= button_to "Edit", edit_post_comment_path(comment.post, comment), class: 'button', method: :get %>
      <%= button_to "Destroy", [comment.post, comment], method: :delete, data: { turbo_confirm: "Are you sure?" } %>
    <% end %>
  </article>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.textarea :body %>
  <%= form.submit %>
<% end %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render "form", post: @post, comment: @comment %>
<% end %>