config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  resources :users, only: %i[] do
    resources :posts, only: %i[index]
  end

  resources :posts do
    resources :comments
  end
  resource :session
  resources :passwords, param: :token
  resources :searches, only: %i[index]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Slow Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.classless.min.css">
    <%= turbo_refresh_method_tag :morph %>
    <%= turbo_refresh_scroll_tag :preserve %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <div style="display: flex; align-items: center; gap: 1rem;">
        <%= link_to image_tag('logo.svg', alt: 'Slow Blog'), root_path %>
        <span><%= content_for(:header_text) || "top page" %></span>
      </div>
      <nav>
        <ul>
          <% if authenticated? %>
            <li><%= link_to 'New Post', new_post_path %></li>
            <li><%= link_to 'Sign Out', session_path, data: { turbo_method: :delete } %></li>
          <% end %>
          <% unless authenticated? %>
            <li><%= link_to 'Sign In', new_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>